apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  #The serviceName field creates a headless service (mongodb in this case), which is used for stable DNS names like mongodb-0.mongodb, mongodb-1.mongodb, etc. Each pod gets a unique DNS entry based on its name and StatefulSet name
  serviceName: "mongodb"
  replicas: 3  # Number of MongoDB instances in the replica set
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:5
          command:
            - "mongod"
            - "--replSet"
            - "myReplicaSet"
            - "--bind_ip"
            - "0.0.0.0"
            - "--port"
            - "27017"
          
