apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-init
spec:
  template:
    spec:
      containers:
        - name: mongo-init
          image: mongo:5
          command: 
            - "bash"
            - "-c"
            - |
              echo "Waiting for MongoDB primary to be available...";
              until nc -z -v -w30 mongodb-0.mongodb:27017; do
                echo "Waiting for MongoDB to be up...";
                sleep 5;
              done;
              echo "MongoDB is ready!";
              mongosh --host mongodb-0.mongodb:27017 --eval 'rs.initiate({
                _id: "myReplicaSet",
                members: [
                  { _id: 0, host: "mongodb-0.mongodb:27017" },
                  { _id: 1, host: "mongodb-1.mongodb:27017" },
                  { _id: 2, host: "mongodb-2.mongodb:27017" }
                ]
              })'
      restartPolicy: OnFailure
  backoffLimit: 4  # Retry up to 4 times
