apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-init
spec:
  template:
    spec:
      containers:
        - name: mongo-init
          image: mongo:5
          command:
            - "bash"
            - "-c"
            - |
              # Wait for the MongoDB pods to be ready
              apt update &&  apt install netcat -y
              until nc -z mongodb-0.mongodb 27017; do
                echo "Waiting for MongoDB to start..."
                sleep 5
              done
              mongo mongodb-0.mongodb:27017 <<EOF
              rs.initiate({
                _id: "rs0",
                members: [
                  { _id: 0, host: 'mongodb-0.mongodb:27017' },
                  { _id: 1, host: 'mongodb-1.mongodb:27017' },
                  { _id: 2, host: 'mongodb-2.mongodb:27017' }
                ]
              })
              EOF
      restartPolicy: Never
  backoffLimit: 4  # Retry up to 4 times if it fails
