apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: "mongodb"
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        command:
          - "mongod"
          - "--replSet"
          - "rs0"   # Replace with your replica set name
          - "--bind_ip_all"
  #       volumeMounts:
  #       - name: mongo-data
  #         mountPath: /data/db
  # volumeClaimTemplates:
  # - metadata:
  #     name: mongo-data
  #   spec:
  #     accessModes: ["ReadWriteOnce"]
  #     resources:
  #       requests:
  #         storage: 1Gi
