apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo5-deployment
  namespace: default
  labels:
    app: yolo5
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yolo5
  template:
    metadata:
      labels:
        app: yolo5
    spec:
      containers:
      - name: yolo5
        image: ofekhalabi/yolo5:v1.0.1
        env:
        - name: BUCKET_NAME
          value: "ofekh-yolo5servicedocker-project"
        
