#This will fetch ofekh/polybot/TELEGRAM_TOKEN and store it in a Kubernetes secret:
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: yolo5-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: yolo5-k8s-secret
    creationPolicy: Owner  # Ensure the secret is created and owned by this ExternalSecret
  data:
    - secretKey: SQS_URL
      remoteRef:
        key: ofekh/polybot/SQS_URL
    